language: python
python:
    - 3.6
before_install:
    - pip install flake8
    - pip install tox
    - flake8 .
install:
    - pip install -r requirements.txt
    - python setup.py build
    - python setup.py install
script:
    - tox
